export const offices = [
  {
    name: "Studiotech Belgium",
    manager: "Nicolas Tardieu",
    address: "Houtweg 7, 1130 Brussels",
    city: "Brussels",
    country: "Belgium",
    region: "Europe",
    lat: 50.8823,
    lng: 4.4076,
    phone: "+32 2 266 13 80",
    email: "info@studiotech.be",
    website: "https://www.studiotech.be",
  },
  {
    name: "Studiotech France",
    manager: "Pascal Cima",
    address: "Rue La Boétie 128, 75008 Paris",
    city: "Paris",
    country: "France",
    region: "Europe",
    lat: 48.8748,
    lng: 2.3095,
    phone: "+33 9 72 46 74 51",
    email: "info@studiotech-av.fr",
    website: "https://www.studiotech-av.fr",
  },
  {
    name: "Studiotech Hungary",
    manager: "Karoly Orosz",
    address: "Szentendrei út 285, 1039 Budapest",
    city: "Budapest",
    country: "Hungary",
    region: "Europe",
    lat: 47.5625,
    lng: 19.0453,
    phone: "+36 1 240 14 44",
    email: "studiotech@studiotech.hu",
    website: "https://www.studiotech.hu",
  },
  {
    name: "Studiotech Poland",
    manager: "Elwira Machowska",
    address: "Ulica Bazancia 53, 02-892 Warszawa",
    city: "Warsaw",
    country: "Poland",
    region: "Europe",
    lat: 52.2297,
    lng: 21.0122,
    phone: "+48 22 644 10 25",
    email: "studiotech@studiotech.pl",
    website: "https://www.studiotech.pl",
  },
  {
    name: "Studiotech Maghreb",
    manager: "Sonia Djilali",
    address: "Rue Ismail Chaalal 25, El Mouradia 16070 Alger",
    city: "Algiers",
    country: "Algeria",
    region: "Africa",
    lat: 36.7529,
    lng: 3.042,
    phone: "+213 23 52 64 28",
    email: "info-dz@studiotech.be",
    website: "https://www.studiotech.dz",
  },
  {
    name: "Studiotech Maroc",
    manager: "Bouchaib Amezzargou",
    address: "Rue Al Kassous 9, Secteur 11-M9, Hay Ryad Rabat",
    city: "Rabat",
    country: "Morocco",
    region: "Africa",
    lat: 33.9716,
    lng: -6.8498,
    phone: "+212 537 71 69 65",
    email: "bouchaib@studiotech.ma",
    website: "https://www.studiotech.ma",
  },
  {
    name: "Studiotech Australia",
    manager: "Robert Shirey",
    address: "Unit 18/45 Leighton PI, Hornsby NSW 2077",
    city: "Sydney",
    country: "Australia",
    region: "Asia-Pacific",
    lat: -33.7033,
    lng: 151.0993,
    phone: "+61 2 8911 5020",
    email: "info@studiotechau.com",
    website: "https://www.studiotechau.com",
  },
  {
    name: "Studiotech Niger",
    manager: "Moussa Mahamane Doutchi",
    address: "BP 12838, Niamey",
    city: "Niamey",
    country: "Niger",
    region: "Africa",
    lat: 13.5116,
    lng: 2.1254,
    phone: "+227 96 96 14 84",
    email: "doutchi@studiotech.be",
    website: "",
  },
  {
    name: "Studiotech Nigeria",
    manager: "Moussa Mahamane Doutchi",
    address:
      "Nawa Complex Plot 106 & 107, Ahmadu Bello Way, Kado District, Abuja FCT",
    city: "Abuja",
    country: "Nigeria",
    region: "Africa",
    lat: 9.0578,
    lng: 7.4951,
    phone: "+227 96 96 14 84",
    email: "info@studiotech.ng",
    website: "https://www.studiotech.ng",
  },
];
